"""empty message

Revision ID: 275396af908a
Revises: 2ab96a2ca566
Create Date: 2021-05-13 16:10:49.174408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275396af908a'
down_revision = '2ab96a2ca566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time', sa.String(length=200), nullable=False))
    op.drop_column('show', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('time', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('show', 'start_time')
    # ### end Alembic commands ###
